export const APPS = Object.freeze([
  { slug: 'api', name: 'api', category: 'dev', role: 'Shared API', url: 'https://api.zeaz.dev' },
  { slug: 'shipgenai', name: 'ShipGenAI', category: 'creative', role: 'AI media', url: 'https://shipgenai.zeaz.dev' },
  { slug: 'zacademy', name: 'zacademy', category: 'business', role: 'Education', url: 'https://academy.zeaz.dev' },
  { slug: 'zai', name: 'zai', category: 'ai', role: 'AI runtime', url: 'https://zai.zeaz.dev' },
  { slug: 'zai-coder', name: 'zai-coder', category: 'dev', role: 'Developer AI', url: 'https://zai-coder.zeaz.dev' },
  { slug: 'zai-factory', name: 'zai-factory', category: 'ai', role: 'Agent factory', url: 'https://factory.zeaz.dev' },
  { slug: 'zaiz', name: 'zaiz', category: 'ai', role: 'AI application', url: 'https://zaiz.zeaz.dev' },
  { slug: 'zcfdash', name: 'zcfdash', category: 'dev', role: 'Cloudflare ops', url: 'https://zcfdash.zeaz.dev' },
  { slug: 'zchat', name: 'zchat', category: 'business', role: 'Messaging', url: 'https://zchat.zeaz.dev' },
  { slug: 'zcino', name: 'zcino', category: 'other', role: 'Game services', url: 'https://zcino.zeaz.dev' },
  { slug: 'zcloud', name: 'zcloud', category: 'dev', role: 'Cloud ops', url: 'https://zcloud.zeaz.dev' },
  { slug: 'zdash', name: 'zdash', category: 'dev', role: 'Platform ops', url: 'https://zdash.zeaz.dev' },
  { slug: 'zdev', name: 'zdev', category: 'dev', role: 'Developer tools', url: 'https://zdev.zeaz.dev' },
  { slug: 'zeaz-api', name: 'zeaz-api', category: 'dev', role: 'API gateway', url: 'https://zeaz-api.zeaz.dev' },
  { slug: 'zeaz-web', name: 'zeaz-web', category: 'dev', role: 'Public web', url: 'https://www.zeaz.dev' },
  { slug: 'zfbauto', name: 'zfbauto', category: 'ai', role: 'Automation', url: 'https://zfbauto.zeaz.dev' },
  { slug: 'zlinebot', name: 'zlinebot', category: 'business', role: 'Messaging bot', url: 'https://linebot.zeaz.dev' },
  { slug: 'zlms', name: 'zlms', category: 'business', role: 'Learning', url: 'https://zlms.zeaz.dev' },
  { slug: 'zoffice', name: 'zoffice', category: 'business', role: 'Workspace', url: 'https://zoffice.zeaz.dev' },
  { slug: 'zorg', name: 'zorg', category: 'business', role: 'Organization', url: 'https://zorg.zeaz.dev' },
  { slug: 'zow', name: 'zow', category: 'business', role: 'Open work', url: 'https://zow.zeaz.dev' },
  { slug: 'zquest', name: 'zquest', category: 'other', role: 'Quest app', url: 'https://zquest.zeaz.dev' },
  { slug: 'zsp-aitool', name: 'zsp-aitool', category: 'ai', role: 'SaaS automation', url: 'https://zsp-aitool.zeaz.dev' },
  { slug: 'zsticker', name: 'zsticker', category: 'creative', role: 'Creative tools', url: 'https://zsticker.zeaz.dev' },
  { slug: 'ztrader', name: 'ztrader', category: 'finance', role: 'Trading', url: 'https://ztrader.zeaz.dev' },
  { slug: 'zveo', name: 'zveo', category: 'creative', role: 'AI video', url: 'https://zveo.zeaz.dev' },
  { slug: 'zwallet', name: 'zwallet', category: 'finance', role: 'Fintech', url: 'https://zwallet.zeaz.dev' }
]);
